version: '3'
services:

  robot_maintenance:
    build:
      context: ../robot_maintenance/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - /home/ubuntu/capstone/store:/robot_maintenance/store
    restart: on-failure

  app_frontend:
    build:
      context: ../app_frontend/
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - /home/ubuntu/capstone/store:/app_frontend/store
    restart: on-failure


      