version: '3.8'

services:
  notebook:
    build: .
    volumes:
      - ./sample:/sample
    container_name: lab9-notebook
    ports:
      - "8888:8888"
    networks:
      - jupyter_network
    command: [
      "start-notebook.sh", 
      "--NotebookApp.token=''", 
      "--NotebookApp.password=''", 
      "--NotebookApp.allow_origin='*'", 
      "--NotebookApp.allow_remote_access='*'"
      ]
    env_file:
      - .env

networks:
  jupyter_network:
    driver: bridge