version: '3.8'

services:
  mlflow:
    build:
      context: mlflow
      dockerfile: Dockerfile
      args:
        - MLFLOW_HOST
        - MLFLOW_PORT
        - MLFLOW_ARTIFACT_ROOT
        - MLFLOW_BACKEND_URI
    volumes:
      - ./mlflow:/mlflow
    env_file:
      - .env
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - mlflow