version: '3.8'

services:
  fastapi:
    container_name: lab8
    build:
      context: .
      dockerfile: sample/Dockerfile
      args:
        - HF_TOKEN
        - HF_FILE_URL
        - HF_FILE_NAME
    volumes:
      - ./sample:/pickerbot/sample
    command: ["python", "sample/run.py"]
    ports:
      - "5000:5000"
    env_file:
      - .env