version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    ports:
      - "80:80"
    env_file:
      - .env
