version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: sample/Dockerfile
      args:
        - HF_TOKEN
        - HF_FILE_URL
    volumes:
      - ./sample:/pickerbot/sample
    ports:
      - "5000:5000"
    env_file:
      - .env
