[tool.poetry]
name = "app"
version = "0.2.0"
description = ""
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
langchain="*"
transformers="*"
datasets="*"
tiktoken="*"
chromadb="*"
sentence_transformers="*"
requests = "^2.31.0"
llama-cpp-python = "^0.2.61"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
